### PR TITLE
Automatic testing integration

### PR DESCRIPTION
**Pull request by xakdog**
I. Before merge you need to:

- [x] go to https://travis-ci.org and enable it for this repo
- [x] go to https://www.appveyor.com and enable it for this repo
- [x] enable https://github.com/marketplace/appveyor
- [x] enable https://github.com/marketplace/travis-ci
- [ ] comment markdown with badges here (see line 2 of readme.md)
- [ ] I will change links for badges

II. After merge:

- [ ] PROFIT. Build statuses will be shown near commits and on Checks tab

### CODE REVIEW

**Review by zottce — CHANGES_REQUESTED** [review]
Change links (username ZOTTCE) and I'll merge PR

**Comment by xakdog** [comment]
@ZOTTCE I've changed links for travis and appveyor.

There is also badge for appveyor and you need to copy image link 
image

**Comment by zottce** [comment]
There is a markdown code from appveyor `[Build status](https://ci.appveyor.com/project/ZOTTCE/samp-sdk/branch/master)`

**Comment by xakdog** [comment]
Great gob!

**Pull request merged**
